// Actual Electron/app/Deep Chat UI; explicitly simulated authentication and AI.
const {app,BrowserWindow}=require('electron');
const {mkdtempSync,mkdirSync,writeFileSync}=require('node:fs');
const {join,resolve}=require('node:path');
const {pathToFileURL}=require('node:url');
const assert=require('node:assert/strict');
const repo=resolve(__dirname,'../..'),out=join(repo,'output/ai-chat-native');
mkdirSync(out,{recursive:true});const profile=mkdtempSync(join(out,'profile-')),caseFolder=join(profile,'Fictional case');mkdirSync(caseFolder);
mkdirSync(join(caseFolder,'people'));mkdirSync(join(caseFolder,'events'));
writeFileSync(join(caseFolder,'people','alex.md'),'---\ntype: person\nrole: Fictional parent\n---\n# Alex Morgan\nFictional case-map record.');
writeFileSync(join(caseFolder,'people','sam.md'),'---\ntype: person\nrole: Fictional parent\nrelated: [alex]\n---\n# Sam Morgan\nFictional case-map record.');
for(let i=0;i<24;i++)writeFileSync(join(caseFolder,'events',`school-${i+1}.md`),`---\ntype: communication\nevent_id: FICTIONAL-${i+1}\ndate: 2026-09-15\npeople: [alex]\n---\n# Fictional school meeting ${i+1}\nA fictional record linked to [[sam]].`);
app.setPath('userData',profile);app.commandLine.appendSwitch('disable-gpu');
app.on('window-all-closed',()=>{}); // Exit only after assertions and server cleanup report their result.
const shots=[],errors=[],externalRequests=[],checks=[];let server,win;
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const js=expression=>win.webContents.executeJavaScript(expression);
async function until(expression){for(let i=0;i<180;i++){if(await js(expression))return;await pause(40);}throw new Error('UI did not reach '+expression);}
const chat="document.querySelector('deep-chat')";
async function capture(name,width,height,night=false){
  win.setContentSize(width,height);await pause(180);
  await js(`window.CaseForgeScene?.update(new Date(${JSON.stringify(night?'2026-09-17T23:00:00+10:00':'2026-09-17T12:00:00+10:00')}));document.documentElement.dataset.sceneMode=${JSON.stringify(night?'dark':'light')};document.body.dataset.sceneMode=${JSON.stringify(night?'dark':'light')};for(const animation of document.getAnimations())try{animation.finish()}catch{}`);
  await js(`${chat}.scrollToBottom();new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))`);await pause(180);
  await js(`window.CaseForgeScene?.update(new Date(${JSON.stringify(night?'2026-09-17T23:00:00+10:00':'2026-09-17T12:00:00+10:00')}));getComputedStyle(document.documentElement).color;for(const animation of document.getAnimations())try{animation.finish()}catch{};new Promise(resolve=>requestAnimationFrame(resolve))`);
  const geometry=await js(`(()=>{const chat=${chat},root=chat?.shadowRoot;const rect=el=>{const r=el.getBoundingClientRect();return {label:el.getAttribute('aria-label')||el.id||el.textContent.trim().slice(0,45),x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height,opacity:getComputedStyle(el).opacity};};const messages=root.querySelector('#messages');return {width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,panel:rect(document.querySelector('#workspace-context')),chat:rect(chat),input:rect(root.querySelector('[contenteditable]')),messages:messages?{...rect(messages),scrollTop:messages.scrollTop,scrollHeight:messages.scrollHeight}:null,controls:[...document.querySelectorAll('#panel-ai button'),...root.querySelectorAll('.input-button')].filter(el=>el.getBoundingClientRect().width&&getComputedStyle(el).visibility!=='hidden').map(rect)};})()`);
  assert.ok(geometry.scrollWidth<=width+2,`${name}: horizontal page overflow`);assert.ok(geometry.scrollHeight<=height+2,`${name}: vertical page overflow`);
  for(const r of [geometry.panel,geometry.chat,geometry.input,...geometry.controls])assert.ok(r.x>=-1&&r.right<=width+1&&r.y>=-1&&r.bottom<=height+1,`${name}: clipped ${r.label} ${JSON.stringify(r)}`);
  assert.ok(geometry.input.height>=20,`${name}: composer is too short`);
  assert.ok(geometry.input.height<=70,`${name}: empty composer should not stretch into the conversation`);
  assert.ok(geometry.input.width>=geometry.chat.width*.94,`${name}: composer uses the conversation width`);
  const alignment=await js(`(()=>{const panel=document.querySelector('#workspace-context'),register=document.querySelector('.case-desk'),p=panel.getBoundingClientRect(),r=register.getBoundingClientRect();return {top:p.top-r.top,right:p.right-r.right,bottom:p.bottom-r.bottom,panelRadius:getComputedStyle(panel).borderTopRightRadius,registerRadius:getComputedStyle(register).borderTopRightRadius};})()`);
  assert.ok(Math.abs(alignment.top)<2&&Math.abs(alignment.right)<2&&Math.abs(alignment.bottom)<2,`${name}: panel follows the file-register bounds ${JSON.stringify(alignment)}`);
  assert.equal(alignment.panelRadius,alignment.registerRadius,`${name}: matching outer corner radius`);
  geometry.alignment=alignment;
  writeFileSync(join(out,name+'.png'),(await win.webContents.capturePage()).toPNG());shots.push({name,...geometry});
}
async function captureDetails(name,width,height,night=false){
  win.setContentSize(width,height);await pause(180);
  await js(`window.CaseForgeScene?.update(new Date(${JSON.stringify(night?'2026-09-17T23:00:00+10:00':'2026-09-17T12:00:00+10:00')}));document.documentElement.dataset.sceneMode=${JSON.stringify(night?'dark':'light')};document.body.dataset.sceneMode=${JSON.stringify(night?'dark':'light')};for(const animation of document.getAnimations())try{animation.finish()}catch{}`);
  await pause(180);
  await js(`window.CaseForgeScene?.update(new Date(${JSON.stringify(night?'2026-09-17T23:00:00+10:00':'2026-09-17T12:00:00+10:00')}));getComputedStyle(document.documentElement).color;for(const animation of document.getAnimations())try{animation.finish()}catch{};new Promise(resolve=>requestAnimationFrame(resolve))`);
  const geometry=await js(`(()=>{const rect=el=>{const r=el.getBoundingClientRect();return {label:el.getAttribute('aria-label')||el.id||el.textContent.trim().slice(0,45),x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height};};const body=document.querySelector('.case-details-body');return {width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,panel:rect(document.querySelector('#workspace-context')),body:rect(body),bodyOverflow:body.scrollHeight>body.clientHeight,controls:[...document.querySelectorAll('.panel-tabs button,#close-context,.case-details-tools input,.case-details-tools select,.case-details-tools button')].filter(el=>el.getBoundingClientRect().width).map(rect)};})()`);
  writeFileSync(join(out,name+'.png'),(await win.webContents.capturePage()).toPNG());shots.push({name,...geometry});
  assert.ok(geometry.scrollWidth<=width+2&&geometry.scrollHeight<=height+2,`${name}: page overflow`);
  for(const r of [geometry.panel,geometry.body,...geometry.controls])assert.ok(r.x>=-1&&r.right<=width+1&&r.y>=-1&&r.bottom<=height+1,`${name}: clipped ${r.label}`);
  assert.ok(geometry.body.height>100,`${name}: Details content remains usable`);
}
(async()=>{
  await app.whenReady();const {createServer}=await import(pathToFileURL(join(repo,'app/server.js')).href);
  server=createServer(caseFolder,{preview:true});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  for(let i=0;i<12;i++)await server.inbox.import(caseFolder,`Fictional school source ${i+1}.txt`,Buffer.from(`This is fictional school record ${i+1}.`));
  win=new BrowserWindow({show:false,width:1400,height:950,webPreferences:{preload:join(__dirname,'native-ai-chat-preload.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});
  win.webContents.on('console-message',(_event,level,message)=>{if(level>=3)errors.push(message);});
  win.webContents.setWindowOpenHandler(()=>({action:'deny'}));
  win.webContents.session.webRequest.onBeforeRequest((details,callback)=>{const remote=/^https?:/.test(details.url)&&!details.url.startsWith(`http://127.0.0.1:${server.address().port}/`);if(remote)externalRequests.push(details.url);callback({cancel:remote});});
  await win.loadURL(`http://127.0.0.1:${server.address().port}`);
  await until(`document.querySelector('#view .desk-toolbar')`);
  await js(`document.querySelector('#ask-claude').click()`);
  await until(`${chat}?.shadowRoot?.querySelector('[contenteditable]') && !document.querySelector('#chat-login').disabled`);
  const brand=await js(`({background:getComputedStyle(document.querySelector('#chat-login')).backgroundColor,label:document.querySelector('#chat-login').textContent,loaded:document.querySelector('#chat-login img')?.naturalWidth,disabled:${chat}.shadowRoot.querySelector('.input-button')?.outerHTML})`);
  assert.equal(brand.background,'rgb(0, 0, 0)');assert.match(brand.label,/Sign in with ChatGPT/);assert.ok(brand.loaded>0);checks.push('Signed-out black button and local logo loaded');
  await capture('signed-out-desktop-day',1380,890);await capture('signed-out-compact-night',804,619,true);
  await js(`document.querySelector('#chat-login').click()`);await until(`!document.querySelector('#chat-cancel-login').hidden`);
  assert.match(await js(`document.querySelector('.ai-status').textContent`),/Finish signing in/);
  await capture('sign-in-pending-compact-day',804,619);
  await js(`document.querySelector('#chat-cancel-login').click()`);await until(`document.querySelector('#chat-cancel-login').hidden&&!document.querySelector('#chat-login').disabled`);
  assert.equal(await js(`window.caseForgeChatFixture.snapshot().metrics.cancelLogin`),1);
  await js(`document.querySelector('#chat-login').click()`);await until(`!document.querySelector('#chat-cancel-login').hidden`);
  const signedInAt=Date.now();await js(`window.caseForgeChatFixture.completeSignIn()`);await until(`document.querySelector('#panel-ai').dataset.connected==='true'&&document.querySelector('#chat-login').textContent==='Sign out'`);
  assert.ok(Date.now()-signedInAt<1000,'Status push should update without waiting for polling');checks.push('Pending login, cancel, and immediate connected status push');
  assert.equal(await js(`document.querySelector('.ai-connection').getBoundingClientRect().height`),0,'Connected account box is removed from the layout');
  assert.equal(await js(`Boolean(document.querySelector('.ai-chat-note'))`),false,'The redundant message-disclosure footer is removed');
  await capture('connected-desktop-day',1380,890);
  const docked=await js(`(()=>{const r=document.querySelector('#workspace-context').getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};})()`);
  await js(`document.querySelector('#workspace-context .window-grip').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true,cancelable:true}))`);
  assert.equal(await js(`document.querySelector('#workspace-context').dataset.windowMode`),'float');
  await js(`document.querySelector('#workspace-context [data-window-place="right"]').click()`);
  assert.deepEqual(await js(`(()=>{const r=document.querySelector('#workspace-context').getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};})()`),docked,'Redocking restores original bounds after keyboard floating');
  await js(`document.querySelector('#workspace-context [data-window-place="float"]').click()`);
  assert.ok(await js(`(()=>{const r=document.querySelector('#workspace-context').getBoundingClientRect();return Math.abs(r.x+r.width/2-innerWidth/2)<2&&r.top>=0&&r.bottom<=innerHeight;})()`),'Floating panel is centred and remains on screen');
  await js(`document.querySelector('#workspace-context [data-window-place="left"]').click()`);
  assert.ok(await js(`Math.abs(document.querySelector('#workspace-context').getBoundingClientRect().left-document.querySelector('.case-desk').getBoundingClientRect().left)<2`),'Left docking follows the register edge');
  await js(`document.querySelector('#workspace-context [data-window-place="right"]').click()`);checks.push('Keyboard floating and left/right docking restore the aligned panel bounds');
  await js(`window.caseForgeChatFixture.setMode('thinking');${chat}.shadowRoot.querySelector('[contenteditable]').focus()`);
  win.webContents.focus();
  await win.webContents.insertText('Explain this fictional example.');
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Return',modifiers:['shift']});win.webContents.sendInputEvent({type:'char',keyCode:'\r',modifiers:['shift']});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Return',modifiers:['shift']});await pause(50);
  await win.webContents.insertText('Use source dates.');
  assert.match(await js(`${chat}.shadowRoot.querySelector('[contenteditable]').innerText`),/example\.\nUse source dates\./,'Shift+Enter creates a new line');
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Return'});win.webContents.sendInputEvent({type:'char',keyCode:'\r'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Return'});
  await until(`window.caseForgeChatFixture.snapshot().metrics.chats.length===1`);
  assert.equal(await js(`${chat}.shadowRoot.querySelector('[contenteditable]').textContent`),'','The submitted composer clears immediately');
  assert.equal(await js(`window.caseForgeChatFixture.snapshot().metrics.chats[0].text`),'Explain this fictional example.\nUse source dates.');checks.push('Actual native typing supports Shift+Enter, Enter submission and immediate input clearing');
  assert.ok(await js(`${chat}.shadowRoot.querySelector('.ai-typing')`),'Custom typing indicator is visible');
  assert.equal(await js(`getComputedStyle(${chat}.shadowRoot.querySelector('#chat-stop-icon').closest('.input-button')).opacity`),'1','Stop remains visually enabled');
  assert.match(await js(`${chat}.shadowRoot.querySelector('#chat-stop-icon').closest('.input-button').getAttribute('aria-label')||''`),/Stop/i,'Stop has an accessible name');
  assert.equal(await js(`${chat}.shadowRoot.querySelector('.deep-chat-intro').getBoundingClientRect().height`),0,'Intro is removed after the first message');
  await capture('typing-compact-day',804,619);
  await until(`window.caseForgeChatFixture.snapshot().metrics.progress.some(p=>p.phase==='delta')`);
  await until(`${chat}.shadowRoot.textContent.includes('Fictional streamed')`);
  assert.ok(!(await js(`${chat}.getMessages().at(-1)?.text||''`)).includes('Unsafe source'),'First partial reply must render before the final reply');
  await capture('streaming-desktop-night',1380,890,true);
  await until(`document.querySelector('.ai-status').textContent.includes('Reply complete')`);
  const response=await js(`({messages:${chat}.getMessages(),expected:window.caseForgeChatFixture.snapshot().answer,html:${chat}.shadowRoot.innerHTML,injected:window.chatInjection||false})`);
  assert.equal(response.messages.filter(m=>m.role==='ai').at(-1).text,response.expected,'Cumulative stream events must not duplicate text');
  assert.equal(response.injected,false);assert.ok(!await js(`${chat}.shadowRoot.querySelector('script')`));assert.ok(await js(`[...${chat}.shadowRoot.querySelectorAll('strong')].some(node=>node.textContent.includes('Fictional streamed'))`));checks.push('Partial model progress renders, final message is not duplicated, Markdown renders and HTML stays inert');
  const links=await js(`(()=>{const root=${chat}.shadowRoot;const all=[...root.querySelectorAll('a')];const safe=all.find(a=>a.textContent==='Safe source'),unsafe=all.find(a=>a.textContent==='Unsafe source');if(!safe||!unsafe)return {found:false,html:root.innerHTML};unsafe.click();safe.click();return {found:true};})()`);
  assert.equal(links.found,true);assert.deepEqual(await js(`window.caseForgeChatFixture.snapshot().metrics.openedLinks`),['https://example.com/fictional']);checks.push('Unsafe link blocked; safe link uses external-link bridge');
  await capture('reply-desktop-day',1380,890);await capture('reply-compact-night',804,619,true);
  const count=await js(`${chat}.getMessages().length`);await js(`document.querySelector('#close-context').click();document.querySelector('#ask-claude').click()`);await until(`!document.querySelector('#workspace-context').hidden`);assert.equal(await js(`${chat}.getMessages().length`),count);checks.push('Conversation survives closing and reopening its pane');
  await js(`document.querySelector('[data-panel="details"]').click()`);await until(`!document.querySelector('#panel-details').hidden&&document.querySelectorAll('.case-details-results [data-detail-select]').length===26`);
  assert.equal(await js(`[...document.querySelectorAll('.panel-tabs button')].filter(el=>el.getBoundingClientRect().width>0).length`),2,'Both tabs remain available on Details');
  await captureDetails('details-desktop-day',1380,890);await captureDetails('details-compact-night',804,619,true);
  await js(`const input=document.querySelector('#case-details-query');input.value='school-1.md';input.dispatchEvent(new Event('input',{bubbles:true}));const type=document.querySelector('#case-details-type');type.value='event';type.dispatchEvent(new Event('change',{bubbles:true}));input.focus();input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));`);
  await until(`document.querySelector('.case-details-selection h3')?.textContent==='Fictional school meeting 1'`);
  assert.equal(await js(`document.querySelectorAll('.case-details-results [data-detail-select]').length`),1);
  assert.equal(await js(`document.querySelectorAll('.case-details-map [data-detail-select]').length`),3,'Compact map displays the selected event and its two recorded people');
  assert.match(await js(`document.querySelector('.case-details-selection').textContent`),/2 recorded connections/);
  await captureDetails('details-selected-compact-day',804,619);
  await js(`document.querySelector('.case-details-body').scrollTop=120;window.savedDetailsScroll=document.querySelector('.case-details-body').scrollTop;document.querySelector('[data-panel="ai"]').click()`);
  assert.equal(await js(`${chat}.getMessages().length`),count,'Switching Details retains chat history');
  assert.equal(await js(`[...document.querySelectorAll('.panel-tabs button')].filter(el=>el.getBoundingClientRect().width>0).length`),2,'Both tabs remain available on AI chat');
  await js(`document.querySelector('[data-panel="details"]').click();document.querySelector('#close-context').click();document.querySelector('#toggle-context').click()`);
  assert.equal(await js(`document.querySelector('#case-details-query').value`),'school-1.md');assert.equal(await js(`document.querySelector('#case-details-type').value`),'event');
  assert.equal(await js(`document.querySelector('.case-details-selection h3').textContent`),'Fictional school meeting 1');
  assert.equal(await js(`document.querySelector('.case-details-body').scrollTop`),await js(`window.savedDetailsScroll`),'Details scroll survives tab switching and close/reopen');
  checks.push('Details searches the actual local case graph, shows recorded links and retains query, filter, selection and scroll across both tabs and close/reopen');
  await js(`(()=>{const input=document.querySelector('#case-details-query');input.focus();input.select();})()`);win.webContents.focus();await win.webContents.insertText('school-2.md');
  await until(`document.querySelector('.case-details-results [data-detail-select="events/school-2.md"]')`);
  const point=await js(`(()=>{document.querySelector('.case-details-body').scrollTop=9999;const r=document.querySelector('.case-details-results [data-detail-select="events/school-2.md"]').getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)};})()`);
  win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...point});win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...point});
  await until(`document.querySelector('.case-details-selection h3')?.textContent==='Fictional school meeting 2'`);checks.push('First pointer click after editing and blurring Details search selects the intended record');
  await js(`document.querySelector('.case-details-selection [data-detail-map]').click()`);await until(`document.querySelector('#map-details h2')?.textContent==='Fictional school meeting 2'`);
  assert.equal(await js(`document.querySelector('#workspace-context').hidden`),false,'Opening the full map keeps Details present');
  await js(`document.querySelector('[data-map-mode="list"]').click();document.querySelector('#map-list [data-map-select="people/sam.md"]').click()`);
  await until(`document.querySelector('.case-details-selection h3')?.textContent==='Sam Morgan'`);
  assert.equal(await js(`document.querySelector('#case-details-query').value`),'school-2.md','Full-map tracking does not erase the Details query');
  assert.equal(await js(`getComputedStyle(document.querySelector('#map-details')).display`),'none','Persistent Details replaces the duplicate legacy map inspector');
  assert.equal(await js(`getComputedStyle(document.querySelector('#workspace-context')).borderTopRightRadius`),'14px','Map surfaces retain rounded inspector corners');
  await js(`document.querySelector('[data-panel="ai"]').click()`);
  assert.ok(await js(`document.querySelector('#map-details').getBoundingClientRect().height>0`),'The selected map record is available again beside AI chat');
  await js(`document.querySelector('[data-panel="details"]').click()`);
  assert.equal(await js(`getComputedStyle(document.querySelector('#map-details')).display`),'none');
  await js(`document.querySelector('#close-context').click()`);
  assert.ok(await js(`document.querySelector('#map-details').getBoundingClientRect().height>0`),'Closing the case panel restores the selected map record inspector');
  await js(`document.querySelector('#toggle-context').click()`);
  assert.equal(await js(`getComputedStyle(document.querySelector('#map-details')).display`),'none');
  checks.push('Duplicate map inspector hides only for open Details and returns for AI chat or a closed case panel');
  await js(`document.querySelector('.case-details-body').scrollTop=0`);
  await captureDetails('details-with-full-map-day',1380,890);await captureDetails('details-with-full-map-compact-night',804,619,true);
  await js(`document.querySelector('[data-view="dashboard"]').click()`);await until(`document.querySelector('#view .desk-toolbar')`);
  assert.equal(await js(`document.querySelector('#workspace-context').hidden`),false,'Navigation preserves the Details panel');checks.push('Full map and Details synchronize selected records while navigation preserves the inspector and search');
  await js(`document.querySelector('[data-panel="ai"]').click()`);
  await js(`window.caseForgeChatFixture.setMode('overwrite');${chat}.submitUserMessage({text:'Replace the fictional progress commentary with the final answer.'})`);
  await until(`${chat}.shadowRoot.textContent.includes('I will think through this fictional record.')`);
  await until(`document.querySelector('.ai-status').textContent.includes('Reply complete')`);
  const replacement=await js(`${chat}.getMessages().filter(message=>message.role==='ai').at(-1).text`);
  assert.equal(replacement,'A fictional reply replaces the progress commentary.');checks.push('An authoritative non-prefix final stream replaces progress commentary');
  await capture('replacement-desktop-night',1380,890,true);
  await js(`window.caseForgeChatFixture.setMode('stop');${chat}.submitUserMessage({text:'Start a fictional long reply.'})`);await until(`${chat}.shadowRoot.textContent.includes('Fictional partial reply')`);
  await js(`${chat}.shadowRoot.querySelector('#chat-stop-icon').closest('.input-button').click()`);await until(`document.querySelector('.ai-status').textContent==='Reply stopped.'`);assert.equal(await js(`window.caseForgeChatFixture.snapshot().metrics.cancel`),1);checks.push('Custom Stop button cancels the in-flight fictional request');
  await capture('stopped-compact-day',804,619);
  await js(`document.querySelector('#chat-new').click()`);await until(`window.caseForgeChatFixture.snapshot().metrics.newConversation===1&&${chat}.getMessages().length===0`);checks.push('New conversation clears the displayed history');
  await js(`document.querySelector('.ai-session-menu summary').click();document.querySelector('#chat-signout').click()`);await until(`document.querySelector('#panel-ai').dataset.connected==='false'`);checks.push('Compact account menu signs out and immediately clears the connected state');
  assert.equal(externalRequests.length,0,externalRequests.join('\n'));assert.equal(errors.length,0,errors.join('\n'));
  writeFileSync(join(out,'report.json'),JSON.stringify({ok:true,simulatedAI:true,realAuthentication:false,realInference:false,checks,shots,errors,externalRequests,fixture:await js(`window.caseForgeChatFixture.snapshot()`),completedAt:new Date().toISOString()},null,2));console.log(JSON.stringify({ok:true,simulatedAI:true,captures:shots.length,checks:checks.length,output:out}));
})().catch(async error=>{console.error(error.stack);const ui=win&&!win.isDestroyed()?await js(`({html:document.querySelector('#panel-ai')?.innerHTML,shadow:${chat}?.shadowRoot?.innerHTML,fixture:window.caseForgeChatFixture?.snapshot()})`).catch(()=>null):null;writeFileSync(join(out,'failure.json'),JSON.stringify({ok:false,simulatedAI:true,error:error.message,checks,shots,errors,externalRequests,ui},null,2));process.exitCode=1;}).finally(async()=>{win?.destroy();await server?.closeWorkspace();if(server)await new Promise(resolve=>server.close(resolve));app.exit(process.exitCode||0);});
