// Actual Electron/app/Deep Chat UI; explicitly simulated authentication and AI.
const {app,BrowserWindow}=require('electron');
const {mkdtempSync,mkdirSync,writeFileSync}=require('node:fs');
const {join,resolve}=require('node:path');
const {pathToFileURL}=require('node:url');
const assert=require('node:assert/strict');
const repo=resolve(__dirname,'../..'),out=join(repo,'output/ai-chat-native');
mkdirSync(out,{recursive:true});const profile=mkdtempSync(join(out,'profile-')),caseFolder=join(profile,'Fictional case');mkdirSync(caseFolder);
app.setPath('userData',profile);app.commandLine.appendSwitch('disable-gpu');
const shots=[],errors=[],externalRequests=[],checks=[];let server,win;
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const js=expression=>win.webContents.executeJavaScript(expression);
async function until(expression){for(let i=0;i<180;i++){if(await js(expression))return;await pause(40);}throw new Error('UI did not reach '+expression);}
const chat="document.querySelector('deep-chat')";
async function capture(name,width,height,night=false){
  win.setContentSize(width,height);await pause(180);
  await js(`window.CaseForgeScene?.update(new Date(${JSON.stringify(night?'2026-09-17T23:00:00+10:00':'2026-09-17T12:00:00+10:00')}));document.documentElement.dataset.sceneMode=${JSON.stringify(night?'dark':'light')};document.body.dataset.sceneMode=${JSON.stringify(night?'dark':'light')};for(const animation of document.getAnimations())try{animation.finish()}catch{}`);
  await js(`${chat}.scrollToBottom();new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))`);await pause(180);
  const geometry=await js(`(()=>{const chat=${chat},root=chat?.shadowRoot;const rect=el=>{const r=el.getBoundingClientRect();return {label:el.getAttribute('aria-label')||el.id||el.textContent.trim().slice(0,45),x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height,opacity:getComputedStyle(el).opacity};};const messages=root.querySelector('#messages');return {width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,panel:rect(document.querySelector('#workspace-context')),chat:rect(chat),input:rect(root.querySelector('[contenteditable]')),messages:messages?{...rect(messages),scrollTop:messages.scrollTop,scrollHeight:messages.scrollHeight}:null,controls:[...document.querySelectorAll('#panel-ai button'),...root.querySelectorAll('.input-button')].filter(el=>el.getBoundingClientRect().width&&getComputedStyle(el).visibility!=='hidden').map(rect)};})()`);
  assert.ok(geometry.scrollWidth<=width+2,`${name}: horizontal page overflow`);assert.ok(geometry.scrollHeight<=height+2,`${name}: vertical page overflow`);
  for(const r of [geometry.panel,geometry.chat,geometry.input,...geometry.controls])assert.ok(r.x>=-1&&r.right<=width+1&&r.y>=-1&&r.bottom<=height+1,`${name}: clipped ${r.label} ${JSON.stringify(r)}`);
  assert.ok(geometry.input.height>=20,`${name}: composer is too short`);
  writeFileSync(join(out,name+'.png'),(await win.webContents.capturePage()).toPNG());shots.push({name,...geometry});
}
(async()=>{
  await app.whenReady();const {createServer}=await import(pathToFileURL(join(repo,'app/server.js')).href);
  server=createServer(caseFolder,{preview:true});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  win=new BrowserWindow({show:false,width:1400,height:950,webPreferences:{preload:join(__dirname,'native-ai-chat-preload.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});
  win.webContents.on('console-message',(_event,level,message)=>{if(level>=3)errors.push(message);});
  win.webContents.setWindowOpenHandler(()=>({action:'deny'}));
  win.webContents.session.webRequest.onBeforeRequest((details,callback)=>{const remote=/^https?:/.test(details.url)&&!details.url.startsWith(`http://127.0.0.1:${server.address().port}/`);if(remote)externalRequests.push(details.url);callback({cancel:remote});});
  await win.loadURL(`http://127.0.0.1:${server.address().port}`);
  await until(`document.querySelector('#view .desk-toolbar')`);
  await js(`document.querySelector('#ask-claude').click()`);
  await until(`${chat}?.shadowRoot?.querySelector('[contenteditable]') && !document.querySelector('#chat-login').disabled`);
  const brand=await js(`({background:getComputedStyle(document.querySelector('#chat-login')).backgroundColor,label:document.querySelector('#chat-login').textContent,loaded:document.querySelector('#chat-login img')?.naturalWidth,disabled:${chat}.shadowRoot.querySelector('.input-button')?.outerHTML})`);
  assert.equal(brand.background,'rgb(0, 0, 0)');assert.match(brand.label,/Sign in with ChatGPT/);assert.ok(brand.loaded>0);checks.push('Signed-out black button and local logo loaded');
  await capture('signed-out-desktop-day',1380,890);await capture('signed-out-compact-night',804,619,true);
  await js(`document.querySelector('#chat-login').click()`);await until(`!document.querySelector('#chat-cancel-login').hidden`);
  assert.match(await js(`document.querySelector('.ai-status').textContent`),/Finish signing in/);
  await capture('sign-in-pending-compact-day',804,619);
  await js(`document.querySelector('#chat-cancel-login').click()`);await until(`document.querySelector('#chat-cancel-login').hidden&&!document.querySelector('#chat-login').disabled`);
  assert.equal(await js(`window.caseForgeChatFixture.snapshot().metrics.cancelLogin`),1);
  await js(`document.querySelector('#chat-login').click()`);await until(`!document.querySelector('#chat-cancel-login').hidden`);
  const signedInAt=Date.now();await js(`window.caseForgeChatFixture.completeSignIn()`);await until(`document.querySelector('#panel-ai').dataset.connected==='true'&&document.querySelector('#chat-login').textContent==='Sign out'`);
  assert.ok(Date.now()-signedInAt<1000,'Status push should update without waiting for polling');checks.push('Pending login, cancel, and immediate connected status push');
  await js(`${chat}.submitUserMessage({text:'Explain this fictional example.'})`);await until(`window.caseForgeChatFixture.snapshot().metrics.progress.some(p=>p.phase==='delta')`);
  await until(`${chat}.shadowRoot.textContent.includes('Fictional streamed')`);
  assert.ok(!(await js(`${chat}.getMessages().at(-1)?.text||''`)).includes('Unsafe source'),'First partial reply must render before the final reply');
  await capture('streaming-desktop-night',1380,890,true);
  await until(`document.querySelector('.ai-status').textContent.includes('Reply complete')`);
  const response=await js(`({messages:${chat}.getMessages(),expected:window.caseForgeChatFixture.snapshot().answer,html:${chat}.shadowRoot.innerHTML,injected:window.chatInjection||false})`);
  assert.equal(response.messages.filter(m=>m.role==='ai').at(-1).text,response.expected,'Cumulative stream events must not duplicate text');
  assert.equal(response.injected,false);assert.ok(!await js(`${chat}.shadowRoot.querySelector('script')`));assert.ok(await js(`[...${chat}.shadowRoot.querySelectorAll('strong')].some(node=>node.textContent.includes('Fictional streamed'))`));checks.push('Partial model progress renders, final message is not duplicated, Markdown renders and HTML stays inert');
  const links=await js(`(()=>{const root=${chat}.shadowRoot;const all=[...root.querySelectorAll('a')];const safe=all.find(a=>a.textContent==='Safe source'),unsafe=all.find(a=>a.textContent==='Unsafe source');if(!safe||!unsafe)return {found:false,html:root.innerHTML};unsafe.click();safe.click();return {found:true};})()`);
  assert.equal(links.found,true);assert.deepEqual(await js(`window.caseForgeChatFixture.snapshot().metrics.openedLinks`),['https://example.com/fictional']);checks.push('Unsafe link blocked; safe link uses external-link bridge');
  await capture('reply-desktop-day',1380,890);await capture('reply-compact-night',804,619,true);
  const count=await js(`${chat}.getMessages().length`);await js(`document.querySelector('#close-context').click();document.querySelector('#ask-claude').click()`);await until(`!document.querySelector('#workspace-context').hidden`);assert.equal(await js(`${chat}.getMessages().length`),count);checks.push('Conversation survives closing and reopening its pane');
  await js(`window.caseForgeChatFixture.setMode('overwrite');${chat}.submitUserMessage({text:'Replace the fictional progress commentary with the final answer.'})`);
  await until(`${chat}.shadowRoot.textContent.includes('I will think through this fictional record.')`);
  await until(`document.querySelector('.ai-status').textContent.includes('Reply complete')`);
  const replacement=await js(`${chat}.getMessages().filter(message=>message.role==='ai').at(-1).text`);
  assert.equal(replacement,'A fictional reply replaces the progress commentary.');checks.push('An authoritative non-prefix final stream replaces progress commentary');
  await capture('replacement-desktop-night',1380,890,true);
  await js(`window.caseForgeChatFixture.setMode('stop');${chat}.submitUserMessage({text:'Start a fictional long reply.'})`);await until(`${chat}.shadowRoot.textContent.includes('Fictional partial reply')`);
  await js(`${chat}.shadowRoot.querySelector('#stop-icon').closest('.input-button').click()`);await until(`document.querySelector('.ai-status').textContent==='Reply stopped.'`);assert.equal(await js(`window.caseForgeChatFixture.snapshot().metrics.cancel`),1);checks.push('Stop button cancels the in-flight fictional request');
  await capture('stopped-compact-day',804,619);
  await js(`document.querySelector('#chat-new').click()`);await until(`window.caseForgeChatFixture.snapshot().metrics.newConversation===1&&${chat}.getMessages().length===0`);checks.push('New conversation clears the displayed history');
  await js(`document.querySelector('#chat-login').click()`);await until(`document.querySelector('#panel-ai').dataset.connected==='false'`);checks.push('Sign out immediately clears the connected state');
  assert.equal(externalRequests.length,0,externalRequests.join('\n'));assert.equal(errors.length,0,errors.join('\n'));
  writeFileSync(join(out,'report.json'),JSON.stringify({ok:true,simulatedAI:true,realAuthentication:false,realInference:false,checks,shots,errors,externalRequests,fixture:await js(`window.caseForgeChatFixture.snapshot()`),completedAt:new Date().toISOString()},null,2));console.log(JSON.stringify({ok:true,simulatedAI:true,captures:shots.length,checks:checks.length,output:out}));
})().catch(async error=>{console.error(error.stack);const ui=win&&!win.isDestroyed()?await js(`({html:document.querySelector('#panel-ai')?.innerHTML,shadow:${chat}?.shadowRoot?.innerHTML,fixture:window.caseForgeChatFixture?.snapshot()})`).catch(()=>null):null;writeFileSync(join(out,'failure.json'),JSON.stringify({ok:false,simulatedAI:true,error:error.message,checks,shots,errors,externalRequests,ui},null,2));process.exitCode=1;}).finally(async()=>{win?.destroy();await server?.closeWorkspace();if(server)await new Promise(resolve=>server.close(resolve));app.exit(process.exitCode||0);});
